#ifndef MYKILIO_H
#define MYKILIO_H

enum mykilio_state {
  MYKILIO_STATE_ABSENT,
  MYKILIO_STATE_DEFERRING,
  MYKILIO_STATE_DISABLED,
  MYKILIO_STATE_ENABLED,
  MYKILIO_STATE_IN_TEST,
  MYKILIO_STATE_QUALIFIED,
  MYKILIO_STATE_QUIESCED,
  MYKILIO_STATE_STANDBY_OFFLINE,
  MYKILIO_STATE_STANDBY_SPARE,
  MYKILIO_STATE_STARTING,
  MYKILIO_STATE_UNAVAILABLE_OFFLINE,
  MYKILIO_STATE_UPDATING,
} mykilio_state_t;

#endif
